name: Download m3u4u EPG

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download-m3u4u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create epg/ folder
        run: |
          mkdir -p epg

      - name: Download and decompress m3u4u EPG into epg/
        run: |
          curl -L "http://m3u4u.com/epg/8p4ey8mr4zuqr983ng1v" -o epg/m3u4u.xml.gz
          gunzip -f epg/m3u4u.xml.gz

      - name: Commit and push epg/m3u4u.xml (if changed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet epg/m3u4u.xml; then
            echo "No changes in epg/m3u4u.xml"
          else
            git add epg/m3u4u.xml
            git commit -m "Update m3u4u EPG"
            git push
          fi