name: Merge EPG

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Ensure universe repo and install xmltv-utils
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y xmltv-utils

      - name: Download EPG sources
        run: |
          curl -L 'https://i.mjh.nz/PlutoTV/us.xml.gz' -o pluto.xml.gz
          gunzip -f pluto.xml.gz
          curl -L 'http://m3u4u.com/epg/8p4ey8mr4zuqr983ng1v' -o bloomberg.xml

      - name: Merge XMLTV into m3u4u.xml
        run: |
          xmltvcat pluto.xml bloomberg.xml > m3u4u.xml

      - name: Compress m3u4u.xml to m3u4u.xml.gz
        run: |
          gzip -9 -f m3u4u.xml

      - name: Verify m3u4u.xml.gz exists
        run: |
          if [ ! -s m3u4u.xml.gz ]; then
            echo "Error: m3u4u.xml.gz is missing or empty" >&2
            exit 1
          fi

      - name: Commit and push m3u4u.xml.gz
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git rm -f m3u4u.xml || true
          git add m3u4u.xml.gz
          if [[ `git status --porcelain m3u4u.xml.gz` ]]; then
            git commit -m "Automated: merge+compress Pluto & Bloomberg → m3u4u.xml.gz"
            git push
          else
            echo "No changes to m3u4u.xml.gz"
          fi
