name: Merge EPG

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install xmltv (xmltvcat)
        run: |
          sudo apt-get update
          sudo apt-get install -y xmltv

      - name: Download EPG sources
        run: |
          curl -L 'https://i.mjh.nz/PlutoTV/us.xml.gz' -o pluto.xml.gz
          gunzip -f pluto.xml.gz
          curl -L 'http://m3u4u.com/epg/8p4ey8mr4zuqr983ng1v' -o bloomberg.xml

      - name: Merge XMLTV into combined.xml
        run: |
          xmltvcat pluto.xml bloomberg.xml > combined.xml

      - name: Verify combined.xml
        run: |
          if [ ! -s combined.xml ]; then
            echo "Error: combined.xml is missing or empty" >&2
            exit 1
          fi

      - name: Commit and push combined.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain combined.xml` ]]; then
            git add combined.xml
            git commit -m "Automated: merge Pluto & Bloomberg XMLTV → combined.xml"
            git push
          else
            echo "No changes to combined.xml"
          fi
