name: merge 2

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge_simplified:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure source EPG files exist
        run: |
          if [ ! -f epg/pluto.xml ] || [ ! -f epg/m3u4u.xml ]; then
            echo "Missing epg/pluto.xml or epg/m3u4u.xml"
            exit 1
          fi

      - name: Merge <programme> and <title> only into epg/combined.xml
        run: |
          python3 - << 'EOF'
import xml.etree.ElementTree as ET

pluto_root = ET.parse('epg/pluto.xml').getroot()
m3u4u_root = ET.parse('epg/m3u4u.xml').getroot()

combined_root = ET.Element('tv')

def extract_simple_programmes(root):
    for prog in root.findall('programme'):
        attrs = {k: prog.get(k) for k in ('start','stop','channel') if prog.get(k)}
        new_prog = ET.Element('programme', attrs)
        title_elem = prog.find('title')
        if title_elem is not None:
            title = ET.SubElement(new_prog, 'title', title_elem.attrib)
            title.text = title_elem.text
        combined_root.append(new_prog)

extract_simple_programmes(pluto_root)
extract_simple_programmes(m3u4u_root)

ET.ElementTree(combined_root).write('epg/combined.xml', encoding='utf-8', xml_declaration=True)
EOF

      - name: Commit and push epg/combined.xml if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet epg/combined.xml; then
            echo "No changes in epg/combined.xml"
          else
            git add epg/combined.xml
            git commit -m "Update simplified combined EPG"
            git push
          fi
