name: Download PlutoTV EPG

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download-pluto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and decompress PlutoTV EPG
        run: |
          curl -L "https://i.mjh.nz/PlutoTV/us.xml.gz" -o pluto.xml.gz
          gunzip -f pluto.xml.gz

      - name: Commit and push pluto.xml (if changed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet pluto.xml; then
            echo "No changes in pluto.xml"
          else
            git add pluto.xml
            git commit -m "Update PlutoTV EPG"
            git push
          fi
